export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const SET_WORDS_SEARCH = 'SET_WORDS_SEARCH';

export const SET_SEARCH_MODE = 'SET_SEARCH_MODE';
export const REMOVE_SEARCH_MODE = 'REMOVE_SEARCH_MODE';

export const SET_SURAT_LIST = 'SET_SURAT_LIST';

export const REVERSE_SURAT_LIST = 'REVERSE_SURAT_LIST';

export const TOGGLE_GO_TO_SURAT_MODAL = 'TOGGLE_GO_TO_SURAT_MODAL';
export const TOGGLE_GO_TO_AYAT_MODAL = 'TOGGLE_GO_TO_AYAT_MODAL';

export const SELECT_AYAT = 'SELECT_AYAT';